#+ summary: Count of 3D Anatomical Structures
#+ description: Count of 3D Anatomical Structures

PREFIX ccf: <http://purl.org/ccf/>

SELECT (COUNT(?x) as ?as_count) WHERE {
  SELECT DISTINCT ?x WHERE {
    ?x a ccf:spatial_entity .
    ?x ccf:has_reference_organ ?y .
	?x ccf:representation_of ?z .
  }
}

