#+ summary: Ref Organ AS count
#+ description: Number of Anatomical Structures per Reference Organ

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>

SELECT (SAMPLE(?organ) AS ?organName) (COUNT(?structure) AS ?asCount)
FROM <https://purl.humanatlas.io/graph/ccf>
WHERE {
  ?structure ccf:has_reference_organ ?organ .
}
GROUP BY ?organ
ORDER BY ?organName
