#+ summary: Reference Organ GLB information
#+ description: Reference Organ GLB information

PREFIX ccf: <http://purl.org/ccf/>
PREFIX ccf-spo: <http://purl.org/ccf/latest/ccf.owl#>

SELECT DISTINCT (STR(?refOrgan) as ?ref_organ) ?glb_url ?scene_node
FROM <https://purl.humanatlas.io/graph/ccf>
WHERE {
  ?n ccf:placement_for ?refOrgan .
  ?n ccf:placement_relative_to ?target .
  ?refOrgan ccf:has_reference_organ ?refOrgan .
  ?refOrgan ccf:has_object_reference [
  	ccf:file_url ?glb_url ;
    ccf:file_subpath ?scene_node  
  ] .
  FILTER ( ?target = ccf-spo:VHFemale || ?target = ccf-spo:VHMale ) 
}
ORDER BY ?ref_organ
