#+ summary: Unique AS, CT, and B in HRA

PREFIX ccf: <http://purl.org/ccf/>
PREFIX CCF: <https://purl.humanatlas.io/graph/ccf>
PREFIX HRAkg: <https://purl.humanatlas.io/collection/hra-kg>

SELECT ?asctb_type (COUNT(DISTINCT(?iri)) as ?count)
FROM CCF:
WHERE {
  ?iri ccf:ccf_asctb_type ?asctb_type
}
GROUP BY ?asctb_type
ORDER BY ?asctb_type
