#+ summary: Unique AS, CT, and B in HRA

PREFIX ccf: <http://purl.org/ccf/>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>

SELECT ?asctb_type (COUNT(DISTINCT(?iri)) as ?count)
FROM HRA:
WHERE {
  ?iri ccf:ccf_asctb_type ?asctb_type
}
GROUP BY ?asctb_type
ORDER BY ?asctb_type
