#+ summary: Biomarkers located in AS

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX has_characterizing_biomarker_set: <http://purl.obolibrary.org/obo/RO_0015004>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>

SELECT DISTINCT ?as ?bm
FROM HRA:
WHERE {
  ?ct ccf:ccf_located_in ?as .

  ?ct rdfs:subClassOf [
  	owl:onProperty has_characterizing_biomarker_set: ;
  	owl:someValuesFrom [ owl:intersectionOf ?bn3 ]] .
  ?bn3 rdf:rest*/rdf:first [
  	owl:onProperty ccf:has_marker_component ;
    owl:someValuesFrom ?bm
  ] .
}
