#+ summary: A lookup table from Ensembl ID to gene name and HGNC ID

PREFIX hgnc: <http://purl.bioontology.org/ontology/HGNC/>
PREFIX hgncId: <http://identifiers.org/hgnc/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX HGNC: <https://purl.humanatlas.io/vocab/hgnc>

SELECT DISTINCT ?ensemble ?gene_name ?hgnc
FROM HGNC:
WHERE
{
  ?hgnc_id oboInOwl:hasDbXref ?ensemble ;
          hgnc:symbol ?gene_name .
  BIND(REPLACE(STR(?hgnc_id), STR(hgncId:), 'HGNC:') as ?hgnc)
  FILTER(STRSTARTS(?ensemble, 'ENS'))
}
ORDER BY ?ensemble
