#+ summary: Unique AS, CT, and B (gene, protein, etc) in HRA

PREFIX ccf: <http://purl.org/ccf/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX hgnc: <http://identifiers.org/hgnc/>

SELECT DISTINCT ?hgnc_id
FROM HRA:
WHERE {
  ?hgnc_iri ccf:ccf_asctb_type ?asctb_type .
  FILTER(?asctb_type = 'BM' && STRSTARTS(STR(?hgnc_iri), STR(hgnc:)))
  BIND(REPLACE(STR(?hgnc_iri), STR(hgnc:), 'HGNC:') as ?hgnc_id)
}
ORDER BY ?hgnc_id
