PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX ctpop: <https://cns-iu.github.io/hra-cell-type-populations-supporting-information/data/enriched_rui_locations.jsonld#graph>
PREFIX iftu: <https://hubmapconsortium.github.io/hra-ui/apps/ftu-ui/assets/TEMP/2d-ftu-illustrations.jsonld>

SELECT *
FROM <https://purl.org/ccf/releases/2.2.1/ccf.owl>
FROM ctpop:
FROM iftu:
WHERE {
  # List of query organ iris
  {
    ?ftu ccf:organ_id ?organ .
    ?ftu rdfs:label ?ftu_label .
    ?ftu ccf:representation_of ?ftu_term .
  }
}
