#+ summary: Find cell parent classes by label
#+ description: Enter a cell type rdfs label, get back a list of parent cell type IRIs and labels

#+ defaults:
#+   - label: "mature B cell"

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX overlaps: <http://purl.obolibrary.org/obo/RO_0002131>
PREFIX cell: <http://purl.obolibrary.org/obo/CL_0000000>

SELECT DISTINCT ?cell STR(?_label_iri) ?parent_cell ?parent_label
WHERE { 
    ?cell rdfs:label STR(?_label_iri) .
    ?cell rdfs:subClassOf cell: .
    ?cell rdfs:subClassOf ?parent_cell .
    ?parent_cell rdfs:subClassOf cell: .
    ?parent_cell rdfs:label ?parent_label .
    
    # FILTER(STR(?label) = ?_label_iri) .
}
