#+ summary: Find cell parent classes by label
#+ description: Enter a cell type rdfs label, get back a list of parent cell type IRIs and labels

#+ defaults:
#+   - qlabel: "mature B cell"

SELECT ?s ?p ?o
WHERE {
    ?_qlabel a rdfs:Literal .
    ?s ?p ?o .
    ?s ?p ?_qlabel .
    FILTER ( STR(?o) = ?_qlabel ) .
}
