#+ summary: Find cell parent classes by label
#+ description: Enter a cell type rdfs label, get back a list of parent cell type IRIs and labels

#+ defaults:
#+   - qlabel: "mature B cell"

SELECT DISTINCT ?o
WHERE {
    ?s ?p ?o .
    FILTER(regex(?o, ?_qlabel, "i")) .
}
