PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ccf: <http://purl.org/ccf/>
PREFIX has_characterizing_biomarker_set: <http://purl.obolibrary.org/obo/RO_0015004>
PREFIX HRA: <https://purl.humanatlas.io/collection/hra>
PREFIX CL: <http://purl.obolibrary.org/obo/CL_>

SELECT DISTINCT ?organ ?cl_id ?cl_label (GROUP_CONCAT(DISTINCT ?gene_symbol;SEPARATOR='; ') as ?gene_symbols) (GROUP_CONCAT(DISTINCT ?hgnc_id;SEPARATOR='; ') as ?hgnc_ids) 
WHERE {
  VALUES (?table ?organ ?ct ?cl_sme_label) {
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000115 "EC-GC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000115 "EC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000235 "MAC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000235 "moMAC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000235 "moMAC-INF")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000236 "B")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000623 "NK")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000653 "POD")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000653 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000786 "PL")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000860 "MON")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0000895 "T")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0002306 "PT")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0002306 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:0002319 "NEU")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000452 "PEC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000692 "FIB")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000692 "altFIB")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000692 "MYOF")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000692 "infFIB")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000698 "resMAC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000768 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000768 "CNT")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000849 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1000849 "DCT")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001106 "MD")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001106 "TAL")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001106 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001107 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001107 "ATL")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001111 "DTL")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001111 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001318 "REN")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001318 "VSMC_PER")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001318 "VSMC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001318 "MC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001431 "PC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:1001431 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:4030015 "IC")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:4030015 "altEPI")
    (<https://purl.humanatlas.io/asct-b/kidney> "Kidney" CL:4052030 "pvFIB")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000097 "MAST")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000235 "MAC-ALV")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000236 "B")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000359 "VSMC")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000576 "MON")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000623 "NK")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000624 "CD4-T")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000625 "CD8-T")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000738 "MAC-INT")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000775 "N")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000786 "PL")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0000814 "NKT")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002062 "AT1")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002063 "AT2")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002063 "AT2.AT1")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002145 "Multicil")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002319 "NEU")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002329 "BASAL")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002394 "cDC1")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0002399 "cDC2")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0009086 "EC-LYM")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0009089 "PER")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:0019019 "ASMC")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:1000223 "NEC")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:1000413 "EC-A")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4028002 "EC-CAP1")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4028003 "EC-CAP2")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4028004 "alvFIB")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4028006 "advFIB")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4033003 "MEC")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4033005 "SER")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4033016 "FB-SCMF")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4033077 "cycMAC-ALV")
    (<https://purl.humanatlas.io/asct-b/lung> "Lung" CL:4033080 "cycAT2")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000097 "Mast cells")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000186 "Myofibroblasts")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000236 "B cells")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000359 "Vascular smooth muscle cells")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000523 "Proliferative CTB")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000523 "Progenitor CTB")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000525 "STB")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0000525 "Proliferative STB progenitors")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0002536 "Amniotic epithelial cells")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0002558 "Proliferative/progenitor fibroblasts")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0002558 "Perivascular fibroblasts")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:0002558 "Stem villus / chorionic plate fibroblasts")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:2000062 "Proliferating endothelial")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:2000062 "Capillary endothelial")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:2000078 "Pericytes")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:3000001 "Proliferative Hofbauer cells")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:3000001 "Hofbauer cells")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:4033062 "Proliferative EVT progenitors")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:4033062 "Invasive EVT")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:4033088 "Decidual macrophages")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:4047006 "Arterial endothelial")
    (<https://purl.humanatlas.io/asct-b/placenta> "Placenta" CL:4047011 "Venous endothelial")
  }
  GRAPH ?table {
    # Find all sets of biomarkers that characterize a cell type
    ?ct rdfs:subClassOf [
      owl:onProperty has_characterizing_biomarker_set: ;
      owl:someValuesFrom [ owl:intersectionOf ?bmSetId ]] .
    ?bmSetId rdf:rest*/rdf:first [
      owl:onProperty ccf:has_marker_component ;
      owl:someValuesFrom ?bm
    ] .

    # Get biomarker type
    ?bm ccf:ccf_biomarker_type ?bmType .
    ?ct ccf:ccf_pref_label ?cl_label .
    ?bm ccf:ccf_pref_label ?gene_symbol .
    
    BIND(REPLACE(STR(?ct), STR(CL:), 'CL:') as ?cl_id)
    BIND(REPLACE(STR(?bm), 'http://identifiers.org/hgnc/', 'HGNC:') as ?hgnc_id)
    FILTER(?bmType = 'gene')
  }
}
GROUP BY ?organ ?cl_id ?cl_label
ORDER BY ?organ ?cl_id ?gene_symbol
